-- Register items to qb-core/shared/items.lua
-- juices

fruit_apple = { 
    name = 'fruit_apple', 
    label = 'Apple', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_apple.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_banana = { 
    name = 'fruit_banana', 
    label = 'Banana', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_banana.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_cherry = { 
    name = 'fruit_cherry', 
    label = 'Cherry', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_cherry.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_currant = { 
    name = 'fruit_currant', 
    label = 'Currant', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_currant.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_grapefruit = { 
    name = 'fruit_grapefruit', 
    label = 'Grapefruit', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_grapefruit.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_kiwi = { 
    name = 'fruit_kiwi', 
    label = 'Kiwi', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_kiwi.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_orange = { 
    name = 'fruit_orange', 
    label = 'Orange', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_orange.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_peach = { 
    name = 'fruit_peach', 
    label = 'Peach', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_peach.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_pear = { 
    name = 'fruit_pear', 
    label = 'Pear', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_pear.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_pineapple = { 
    name = 'fruit_pineapple', 
    label = 'Pineapple', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_pineapple.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_plum = { 
    name = 'fruit_plum', 
    label = 'Plum', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_plum.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
fruit_strawberry = { 
    name = 'fruit_strawberry', 
    label = 'Strawberry', 
    weight = 200, 
    type = 'item', 
    image = 'fruit_strawberry.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},

glass_apple = { 
    name = 'glass_apple', 
    label = 'Glass of apple juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_apple.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Apple juice' 
},
glass_banana = { 
    name = 'glass_banana', 
    label = 'Glass of banana juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_banana.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Banana juice' 
},
glass_cherry = { 
    name = 'glass_cherry', 
    label = 'Glass of cherry juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_cherry.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Cherry juice' 
},
glass_currant = { 
    name = 'glass_currant', 
    label = 'Glass of currant juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_currant.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Currant juice' 
},
glass_grapefruit = { 
    name = 'glass_grapefruit', 
    label = 'Glass of grapefruit juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_grapefruit.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Grapefruit juice' 
},
glass_kiwi = { 
    name = 'glass_kiwi', 
    label = 'Glass of kiwi juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_kiwi.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Kiwi juice' 
},
glass_orange = { 
    name = 'glass_orange', 
    label = 'Glass of orange juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_orange.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Orange juice' 
},
glass_peach = { 
    name = 'glass_peach', 
    label = 'Glass of peach juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_peach.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Peach juice' 
},
glass_pear = { 
    name = 'glass_pear', 
    label = 'Glass of pear juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_pear.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Pear juice' 
},
glass_pineapple = { 
    name = 'glass_pineapple', 
    label = 'Glass of pineapple juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_pineapple.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Pineapple juice' 
},
glass_plum = { 
    name = 'glass_plum', 
    label = 'Glass of plum juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_plum.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Plum juice' 
},
glass_strawberry = { 
    name = 'glass_strawberry', 
    label = 'Glass of strawberry juice', 
    weight = 200, 
    type = 'item', 
    image = 'glass_strawberry.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Strawberry juice' 
},

bzzz_drink_juice_box_apple = { 
    name = 'bzzz_drink_juice_box_apple', 
    label = 'Apple juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_apple.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_banana = { 
    name = 'bzzz_drink_juice_box_banana', 
    label = 'Banana juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_banana.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_cherry = { 
    name = 'bzzz_drink_juice_box_cherry', 
    label = 'Cherry juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_cherry.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_currant = { 
    name = 'bzzz_drink_juice_box_currant', 
    label = 'Currant juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_currant.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_grapefruit = { 
    name = 'bzzz_drink_juice_box_grapefruit', 
    label = 'Grapefruit juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_grapefruit.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_kiwi = { 
    name = 'bzzz_drink_juice_box_kiwi', 
    label = 'Kiwi juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_kiwi.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_orange = { 
    name = 'bzzz_drink_juice_box_orange', 
    label = 'Orange juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_orange.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_peach = { 
    name = 'bzzz_drink_juice_box_peach', 
    label = 'Peach juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_peach.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_pear = { 
    name = 'bzzz_drink_juice_box_pear', 
    label = 'Pear juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_pear.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_pineapple = { 
    name = 'bzzz_drink_juice_box_pineapple', 
    label = 'Pineapple juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_pineapple.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},

bzzz_drink_juice_box_plum = { 
    name = 'bzzz_drink_juice_box_plum', 
    label = 'Plum juice', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_drink_juice_box_plum.png',  
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = ' '  
},
