-- Register items to qb-core/shared/items.lua
-- skewers


shashlik_a = {
    name = 'shashlik_a',
    label = 'Shashlik',
    weight = 350,
    type = 'item',
    image = 'shashlik_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

chicken_intestine_a = {
    name = 'chicken_intestine_a',
    label = 'Chicken Intestine',
    weight = 350,
    type = 'item',
    image = 'chicken-intestine_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

fishball_a = {
    name = 'fishball_a',
    label = 'Fish Ball',
    weight = 350,
    type = 'item',
    image = 'fishball_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

kikiam_a = {
    name = 'kikiam_a',
    label = 'Kikiam',
    weight = 350,
    type = 'item',
    image = 'kikiam_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

black_pudding_a = {
    name = 'black_pudding_a',
    label = 'Black Pudding',
    weight = 350,
    type = 'item',
    image = 'black-pudding_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

quail_eggs_a = {
    name = 'quail_eggs_a',
    label = 'Quail Eggs',
    weight = 350,
    type = 'item',
    image = 'quail-eggs_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

hotdog_a = {
    name = 'hotdog_a',
    label = 'Hotdog',
    weight = 350,
    type = 'item',
    image = 'hotdog_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

banana_a = {
    name = 'banana_a',
    label = 'Banana',
    weight = 350,
    type = 'item',
    image = 'banana_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

pork_bbq_a = {
    name = 'pork_bbq_a',
    label = 'Pork BBQ',
    weight = 350,
    type = 'item',
    image = 'pork-bbq_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

chicken_feet_a = {
    name = 'chicken_feet_a',
    label = 'Chicken Feet',
    weight = 350,
    type = 'item',
    image = 'chicken-feet_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

corn_a = {
    name = 'corn_a',
    label = 'Corn',
    weight = 350,
    type = 'item',
    image = 'corn_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

corndog_a = {
    name = 'corndog_a',
    label = 'Corndog',
    weight = 350,
    type = 'item',
    image = 'corndog_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

fish_a = {
    name = 'fish_a',
    label = 'Fish',
    weight = 350,
    type = 'item',
    image = 'fish_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

cheese_a = {
    name = 'cheese_a',
    label = 'Cheese',
    weight = 350,
    type = 'item',
    image = 'cheese_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

potato_a = {
    name = 'potato_a',
    label = 'Potato',
    weight = 350,
    type = 'item',
    image = 'potato_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},
