-- Register items to qb-core/shared/items.lua
-- xmas



gingerbread = {
    name = 'gingerbread',
    label = 'Gingerbread',
    weight = 350,
    type = 'item',
    image = 'gingerbread.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

xlollipop_a = {
    name = 'xlollipop_a',
    label = 'Xmas Lollipop Red',
    weight = 250,
    type = 'item',
    image = 'xlollipop_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

xlollipop_b = {
    name = 'xlollipop_b',
    label = 'Xmas Lollipop Green',
    weight = 250,
    type = 'item',
    image = 'xlollipop_b.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

xlollipop_c = {
    name = 'xlollipop_c',
    label = 'Xmas Lollipop Purple',
    weight = 250,
    type = 'item',
    image = 'xlollipop_c.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

xlollipop_d = {
    name = 'xlollipop_d',
    label = 'Xmas Lollipop Yellow',
    weight = 250,
    type = 'item',
    image = 'xlollipop_d.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

xlollipop_e = {
    name = 'xlollipop_e',
    label = 'Xmas Lollipop Blue',
    weight = 250,
    type = 'item',
    image = 'xlollipop_e.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

macaroon = {
    name = 'macaroon',
    label = 'Macaroon',
    weight = 250,
    type = 'item',
    image = 'macaroon.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

mug_a = {
    name = 'mug_a',
    label = 'Coffee Cup',
    weight = 250,
    type = 'item',
    image = 'mug_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

mug_b = {
    name = 'mug_b',
    label = 'Tea Cup',
    weight = 250,
    type = 'item',
    image = 'mug_b.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

mulled_wine = {
    name = 'mulled_wine',
    label = 'Mulled Wine',
    weight = 250,
    type = 'item',
    image = 'mulled_wine.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},
