-- Register items to qb-core/shared/items.lua
-- sweetsnack

sweet_cake_a = {
    name = 'sweet_cake_a',
    label = 'Chocolate cake',
    weight = 150,
    type = 'item',
    image = 'cake_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_candy_a = {
    name = 'sweet_candy_a',
    label = 'Skipples',
    weight = 150,
    type = 'item',
    image = 'skipples.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_candy_b = {
    name = 'sweet_candy_b',
    label = 'Little beans',
    weight = 150,
    type = 'item',
    image = 'little_beans.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_chocolate_a = {
    name = 'sweet_chocolate_a',
    label = 'Dark chocolate',
    weight = 150,
    type = 'item',
    image = 'chocolate_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_chocolate_b = {
    name = 'sweet_chocolate_b',
    label = 'White chocolate',
    weight = 150,
    type = 'item',
    image = 'chocolate_b.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_cookie_a = {
    name = 'sweet_cookie_a',
    label = 'Cookie',
    weight = 150,
    type = 'item',
    image = 'cookie_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_lollipop_a = {
    name = 'sweet_lollipop_a',
    label = 'Lollipop',
    weight = 150,
    type = 'item',
    image = 'lollipop_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_lollipop_b = {
    name = 'sweet_lollipop_b',
    label = 'Lollipop heart',
    weight = 150,
    type = 'item',
    image = 'lollipop_b.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_lollipop_c = {
    name = 'sweet_lollipop_c',
    label = 'Lollipop',
    weight = 150,
    type = 'item',
    image = 'lollipop_c.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_lollipop_d = {
    name = 'sweet_lollipop_d',
    label = 'Chocolate lollipop',
    weight = 150,
    type = 'item',
    image = 'lollipop_d.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_snack_a = {
    name = 'sweet_snack_a',
    label = 'Mers',
    weight = 150,
    type = 'item',
    image = 'mers.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_snack_b = {
    name = 'sweet_snack_b',
    label = 'Sneckers',
    weight = 150,
    type = 'item',
    image = 'sneckers.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_snack_c = {
    name = 'sweet_snack_c',
    label = 'Milky',
    weight = 150,
    type = 'item',
    image = 'milky.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_snack_d = {
    name = 'sweet_snack_d',
    label = 'Bouty',
    weight = 150,
    type = 'item',
    image = 'bouty.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_snack_e = {
    name = 'sweet_snack_e',
    label = 'Twinx',
    weight = 150,
    type = 'item',
    image = 'twinx.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_snack_f = {
    name = 'sweet_snack_f',
    label = 'Kitikat',
    weight = 150,
    type = 'item',
    image = 'kitikat.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_wafer_a = {
    name = 'sweet_wafer_a',
    label = 'Wafer',
    weight = 150,
    type = 'item',
    image = 'wafer_a.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

sweet_wafer_b = {
    name = 'sweet_wafer_b',
    label = 'Wafer',
    weight = 150,
    type = 'item',
    image = 'wafer_b.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},
