-- Register items to qb-core/shared/items.lua
-- uwu

bzzz_uwuprops_cake_a = { 
    name = 'bzzz_uwuprops_cake_a', 
    label = 'UwU cake', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_cake_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_cappuccino_a = { 
    name = 'bzzz_uwuprops_cappuccino_a', 
    label = 'Uwu cappuccino', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_cappuccino_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Drink' 
},
bzzz_uwuprops_coffee_a = { 
    name = 'bzzz_uwuprops_coffee_a', 
    label = 'Uwu coffee', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_coffee_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Drink' 
},
bzzz_uwuprops_cookie_a = { 
    name = 'bzzz_uwuprops_cookie_a', 
    label = 'Uwu cookie', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_cookie_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_donut_a = { 
    name = 'bzzz_uwuprops_donut_a', 
    label = 'Uwu donut', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_donut_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_drink_a = { 
    name = 'bzzz_uwuprops_drink_a', 
    label = 'Uwu ice coffee', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_drink_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Drink' 
},
bzzz_uwuprops_drink_b = { 
    name = 'bzzz_uwuprops_drink_b', 
    label = 'Uwu ice coffee', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_drink_b.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Drink' 
},
bzzz_uwuprops_drink_c = { 
    name = 'bzzz_uwuprops_drink_c', 
    label = 'Uwu ice coffee', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_drink_c.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Drink' 
},
bzzz_uwuprops_drink_d = { 
    name = 'bzzz_uwuprops_drink_d', 
    label = 'Uwu ice coffee', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_drink_d.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Drink' 
},
bzzz_uwuprops_icecone_a = { 
    name = 'bzzz_uwuprops_icecone_a', 
    label = 'Uwu ice cream in a cornout', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_icecone_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_icecone_b = { 
    name = 'bzzz_uwuprops_icecone_b', 
    label = 'Uwu ice cream in a cornout', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_icecone_b.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_icecone_c = { 
    name = 'bzzz_uwuprops_icecone_c', 
    label = 'Uwu ice cream in a cornout', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_icecone_c.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_icecone_d = { 
    name = 'bzzz_uwuprops_icecone_d', 
    label = 'Uwu ice cream in a cornout', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_icecone_d.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_icecream_a = { 
    name = 'bzzz_uwuprops_icecream_a', 
    label = 'Uwu ice cream', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_icecream_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_popsicle_a = { 
    name = 'bzzz_uwuprops_popsicle_a', 
    label = 'Uwu popsicle', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_popsicle_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_wafer_a = { 
    name = 'bzzz_uwuprops_wafer_a', 
    label = 'Uwu wafer', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_wafer_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
bzzz_uwuprops_lollipop_a = { 
    name = 'bzzz_uwuprops_lollipop_a', 
    label = 'Uwu lollipop', 
    weight = 200, 
    type = 'item', 
    image = 'bzzz_uwuprops_lollipop_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = 'Food' 
},
