-- Register items to qb-core/shared/items.lua
-- burgershot


bzzz_fastfood_burgershot_drink_a = { 
    name = 'bzzz_fastfood_burgershot_drink_a', 
    label = 'Big drink', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_drink_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_drink_b = { 
    name = 'bzzz_fastfood_burgershot_drink_b', 
    label = 'Small drink', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_drink_b.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_chicken_a = { 
    name = 'bzzz_fastfood_burgershot_chicken_a', 
    label = 'Chicken leg', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_chicken_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_chicken_b = { 
    name = 'bzzz_fastfood_burgershot_chicken_b', 
    label = 'Chicken strip', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_chicken_b.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_icecream_a = { 
    name = 'bzzz_fastfood_burgershot_icecream_a', 
    label = 'Chocolate-vanilla ice cream', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_icecream_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_icecream_b = { 
    name = 'bzzz_fastfood_burgershot_icecream_b', 
    label = 'Raspberry-moon ice cream', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_icecream_b.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_bigburger_a = { 
    name = 'bzzz_fastfood_burgershot_bigburger_a', 
    label = 'Bigburger', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_bigburger_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_cheeseburger_a = { 
    name = 'bzzz_fastfood_burgershot_cheeseburger_a', 
    label = 'Cheeseburger', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_cheeseburger_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_nugget_a = { 
    name = 'bzzz_fastfood_burgershot_nugget_a', 
    label = 'Chicken nugget', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_nugget_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_onion_a = { 
    name = 'bzzz_fastfood_burgershot_onion_a', 
    label = 'Onion ring', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_onion_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_noodle_a = { 
    name = 'bzzz_fastfood_burgershot_noodle_a', 
    label = 'Chinese noodles', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_noodle_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_chicken_d = { 
    name = 'bzzz_fastfood_burgershot_chicken_d', 
    label = 'Chicken legs', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_chicken_d.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_chicken_e = { 
    name = 'bzzz_fastfood_burgershot_chicken_e', 
    label = 'Chicken strips', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_chicken_e.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_chicken_f = { 
    name = 'bzzz_fastfood_burgershot_chicken_f', 
    label = 'Chicken bites', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_chicken_f.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_fries_d = { 
    name = 'bzzz_fastfood_burgershot_fries_d', 
    label = 'Bucket of fries', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_fries_d.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_nugget_b = { 
    name = 'bzzz_fastfood_burgershot_nugget_b', 
    label = 'Chicken nuggets', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_nugget_b.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_onion_b = { 
    name = 'bzzz_fastfood_burgershot_onion_b', 
    label = 'Onion rings', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_onion_b.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_vegesalad_a = { 
    name = 'bzzz_fastfood_burgershot_vegesalad_a', 
    label = 'Vegetarian salad', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_vegesalad_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_fries_a = { 
    name = 'bzzz_fastfood_burgershot_fries_a', 
    label = 'Small fries', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_fries_a.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
bzzz_fastfood_burgershot_fries_b = { 
    name = 'bzzz_fastfood_burgershot_fries_b', 
    label = 'Medium fries', 
    weight = 500, 
    type = 'item', 
    image = 'bzzz_fastfood_burgershot_fries_b.png', 
    unique = false, 
    useable = true, 
    shouldClose = true, 
    combinable = nil, 
    description = '' 
},
