-- Register items to qb-core/shared/items.lua
-- pizza

capricciosa = {
    name = 'capricciosa',
    label = 'Pizza capricciosa',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_capricciosa002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

cheezy = {
    name = 'cheezy',
    label = 'Pizza Cheezy',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_cheezy002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

hawaii = {
    name = 'hawaii',
    label = 'Pizza Hawai',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_hawaii002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

margherita = {
    name = 'margherita',
    label = 'Pizza Margherita',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_margherita002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

marinara = {
    name = 'marinara',
    label = 'Pizza Marinara',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_marinara002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

napoletana = {
    name = 'napoletana',
    label = 'Pizza Napoletana',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_napoletana002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

pepperoni = {
    name = 'pepperoni',
    label = 'Pizza Pepperoni',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_pepperoni002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

funghi = {
    name = 'funghi',
    label = 'Pizza Prosciutto e Funghi',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_prosciutto-e-funghi002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

prosciutto = {
    name = 'prosciutto',
    label = 'Pizza Prosciutto',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_prosciutto002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

formaggi = {
    name = 'formaggi',
    label = 'Pizza Quattro Formaggi',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_quattro-formaggi002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

tonno = {
    name = 'tonno',
    label = 'Pizza Tonno',
    weight = 350,
    type = 'item',
    image = 'bzzz_foodpack_pizza_tonno002.png',
    unique = false,
    useable = true,
    shouldClose = true,
    combinable = nil,
    description = ' ',
},

