INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	/* English Food & Drink */
('bzzz_englishfood_fishchips_b', 'Fish & chips', 1, 0, 0),
('bzzz_englishfood_haggis_a', 'Haggis with mashed potato', 1, 0, 0),
('bzzz_englishfood_tikkamasala_a', 'Chicken Tikka Masala', 1, 0, 0),
('bzzz_englishfood_gammon_a', 'Gammon & Chips', 1, 0, 0),
('bzzz_englishfood_piemash_a', 'Pie & Mash', 1, 0, 0),
('bzzz_englishfood_roastbeef_a', 'Roast Beef & Yorkshire Pudding', 1, 0, 0),
('bzzz_englishfood_breakfast_a', 'English Breakfast', 1, 0, 0),
('bzzz_englishfood_beans_a', 'Beans on Toast', 1, 0, 0),
('bzzz_englishfood_fishchips_a', 'Fish & Chips', 1, 0, 0),
('bzzz_englishfood_bangersmash_a', 'Bangers and Mash', 1, 0, 0),
('bzzz_englishfood_shepherdspie_a', 'Shepherd''s Pie', 1, 0, 0),
('bzzz_englishfood_porkpie_a', 'Pork Pie', 1, 0, 0),
('bzzz_englishfood_sausageroll_a', 'Sausage Roll', 1, 0, 0),
('bzzz_englishfood_sandwich_a', 'Bacon Sandwich', 1, 0, 0),
('bzzz_englishfood_sandwich_c', 'Sausage Sandwich', 1, 0, 0),
('bzzz_englishfood_toffee_a', 'Sticky Toffee Pudding', 1, 0, 0),
('bzzz_englishfood_sponge_a', 'Victoria Sponge', 1, 0, 0),
('bzzz_englishfood_scone_a', 'Scone', 1, 0, 0),
('bzzz_englishfood_shortbread_a', 'Shortbread', 1, 0, 0),
('bzzz_englishfood_jammiedodger_a', 'Jammie Dodger', 1, 0, 0),
('bzzz_englishfood_digestive_a', 'Digestive Biscuits', 1, 0, 0),
('bzzz_englishfood_chips_a', 'Chips - Ready Salted', 1, 0, 0),
('bzzz_englishfood_chips_b', 'Chips - Cheese & Onion', 1, 0, 0),
('bzzz_englishfood_chips_c', 'Chips - Salt & Vinegar', 1, 0, 0),
('bzzz_englishfood_applecrumble_a', 'Apple Crumble', 1, 0, 0),
('bzzz_englishfood_cornishpasty_a', 'Cornish Pasty', 1, 0, 0),
('bzzz_englishfood_chocolate_b', 'KrisKat', 1, 0, 0),
('bzzz_englishfood_chocolate_a', 'Chocolate', 1, 0, 0),
('bzzz_englishfood_beer_a', 'Beer', 1, 0, 0),
('bzzz_englishfood_ironix_a', 'Ironix', 1, 0, 0),
('bzzz_englishfood_ironix_b', 'Ironix Zero', 1, 0, 0),
('bzzz_englishfood_tea_b', 'English Tea', 1, 0, 0);
