INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	/* Food @ drink*/
('bzzz_sushi_beefbroccoli_a', 'Beef and Broccoli', 1, 0, 0),
('bzzz_sushi_coconutshrimp_b', 'Coconut Shrimp', 1, 0, 0),
('bzzz_sushi_crabcakes_b', 'Crab cakes', 1, 0, 0),
('bzzz_sushi_cuttlefishrisotto_b', 'Cuttlefish Risotto', 1, 0, 0),
('bzzz_sushi_ebi_b', 'Sushi Ebi', 1, 0, 0),
('bzzz_sushi_edamame_a', 'Edamame', 1, 0, 0),
('bzzz_sushi_friedcalamari_b', 'Fried Calamari', 1, 0, 0),
('bzzz_sushi_grilledoctopus_b', 'Grilled Octopus', 1, 0, 0),
('bzzz_sushi_hotate_b', 'Sushi Hotate', 1, 0, 0),
('bzzz_sushi_ika_b', 'Sushi Ika', 1, 0, 0),
('bzzz_sushi_kani_b', 'Sushi Kani', 1, 0, 0),
('bzzz_sushi_lobsterbisque_a', 'Lobster Bisque', 1, 0, 0),
('bzzz_sushi_lobstertail_b', 'Lobster tail', 1, 0, 0),
('bzzz_sushi_maguro_b', 'Sushi Maguro', 1, 0, 0),
('bzzz_sushi_mochi_a', 'Mochi', 1, 0, 0),
('bzzz_sushi_momo_a', 'Momo', 1, 0, 0),
('bzzz_sushi_mooncake_a', 'Mooncake', 1, 0, 0),
('bzzz_sushi_moulesmarinieres_a', 'Moules Marinières', 1, 0, 0),
('bzzz_sushi_oystersonice_a', 'Oysters on Ice', 1, 0, 0),
('bzzz_sushi_ramen_a', 'Ramen', 1, 0, 0),
('bzzz_sushi_roll_california_b', 'California Roll', 1, 0, 0),
('bzzz_sushi_roll_cucumbermaki_b', 'Cucumber Maki', 1, 0, 0),
('bzzz_sushi_roll_dragon_b', 'Dragon Roll', 1, 0, 0),
('bzzz_sushi_roll_negitoromaki_b', 'Negitoro Maki', 1, 0, 0),
('bzzz_sushi_roll_philadelphia_b', 'Philadelphia Roll', 1, 0, 0),
('bzzz_sushi_roll_rainbow_b', 'Rainbow Roll', 1, 0, 0),
('bzzz_sushi_roll_sakemaki_b', 'Sake Maki', 1, 0, 0),
('bzzz_sushi_roll_shrimptempura_b', 'Shrimp Tempura Roll', 1, 0, 0),
('bzzz_sushi_roll_spicytuna_b', 'Spicy Tuna Roll', 1, 0, 0),
('bzzz_sushi_roll_tekkamaki_b', 'Tekka Maki', 1, 0, 0),
('bzzz_sushi_sake_b', 'Sake Sushi', 1, 0, 0),
('bzzz_sushi_softshellcrab_b', 'Soft Shell Crab', 1, 0, 0),
('bzzz_sushi_springroll_b', 'Spring roll', 1, 0, 0),
('bzzz_sushi_tako_b', 'Tako Sushi', 1, 0, 0),
('bzzz_sushi_tamago_b', 'Tamago Sushi', 1, 0, 0),
('bzzz_sushi_tempurashrimp_b', 'Tempura Shrimp', 1, 0, 0),
('bzzz_sushi_unagi_b', 'Unagi Sushi', 1, 0, 0),
('bzzz_sushi_brown_sugar_milk_tea_a', 'Brown sugar milk tea', 1, 0, 0),
('bzzz_sushi_classic_milk_tea_a', 'Classic milk tea', 1, 0, 0),
('bzzz_sushi_matcha_milk_tea_a', 'Matcha milk tea', 1, 0, 0),
('bzzz_sushi_strawberry_milk_tea_a', 'Strawberry milk tea', 1, 0, 0),
('bzzz_sushi_taro_milk_tea_a', 'Taro milk tea', 1, 0, 0),
('bzzz_sushi_thai_milk_tea_a', 'Thai milk tea', 1, 0, 0);
